'use client';

import { useState, useEffect, useRef } from 'react';

interface PinnedCommentDraftProps {
  channelName: string;
  videoTitle: string;
  topComments: string;
  dominantCategory: string;
  helpSeekingCount: number;
  bookingIntentCount: number;
  dominantConcern: string;
  highIntentCount: number;
  autoGenerate?: boolean;
}

export default function PinnedCommentDraft(props: PinnedCommentDraftProps) {
  const [comment, setComment] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/generate-comment', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          channelName: props.channelName,
          videoTitle: props.videoTitle,
          topComments: props.topComments,
          dominantCategory: props.dominantCategory,
          helpSeekingCount: props.helpSeekingCount,
          bookingIntentCount: props.bookingIntentCount,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setComment(data.comment);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to generate comment');
    } finally {
      setIsLoading(false);
    }
  };

  // Auto-generate on mount if requested
  useEffect(() => {
    if (props.autoGenerate && !hasAutoGenerated.current && !comment && !isLoading) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.autoGenerate]);

  const handleCopy = async () => {
    if (comment) {
      await navigator.clipboard.writeText(comment);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-2">
      <h4 className="text-sm font-medium text-slate-300">Pinned Comment Draft</h4>

      {isLoading && (
        <div className="bg-slate-800/50 rounded-md p-4 flex items-center gap-2 text-sm text-slate-400">
          <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          Generating pinned comment...
        </div>
      )}

      {error && (
        <div className="text-sm text-rose-400 bg-rose-500/10 rounded-md p-3 border border-rose-500/20">
          {error}
        </div>
      )}

      {comment && (
        <div className="space-y-2">
          <div className="bg-slate-800 rounded-md p-4 text-sm text-slate-200 leading-relaxed border border-slate-700">
            {comment}
          </div>
          <div className="flex items-center justify-between">
            <p className="text-xs text-slate-500">
              This comment addresses the {props.dominantConcern} concern visible in {props.highIntentCount} comments and converts interest into a consultation link.
            </p>
            <div className="flex items-center gap-2 flex-shrink-0 ml-3">
              <button
                onClick={handleGenerate}
                disabled={isLoading}
                className="px-3 py-1.5 text-xs bg-slate-800 hover:bg-slate-700 text-slate-400 rounded border border-slate-700 transition-colors"
              >
                Regenerate
              </button>
              <button
                onClick={handleCopy}
                className="px-3 py-1.5 text-xs bg-slate-800 hover:bg-slate-700 text-slate-300 rounded border border-slate-700 transition-colors"
              >
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
